import "@/app/globals.css";
import { SidebarProvider } from "@/components/ui/sidebar";
import AdminSidebar from "@/features/Admin/AdminSidebar";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} flex min-h-screen flex-col antialiased`}
      >
        <SidebarProvider>
          <aside>
            <AdminSidebar />
          </aside>
          <main className="">{children}</main>
        </SidebarProvider>
      </body>
    </html>
  );
}
