import "@/app/globals.css";
import { SidebarProvider } from "@/components/ui/sidebar";
import AdminSidebar from "@/features/Admin/AdminSidebar";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <SidebarProvider>
      <aside>
        <AdminSidebar />
      </aside>
      <main className="w-full">{children}</main>
    </SidebarProvider>
  );
}
