import "@/app/globals.css";
import { SidebarProvider } from "@/components/ui/sidebar";
import AdminSidebar from "@/features/Admin/AdminSidebar";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <SidebarProvider>
      <aside>
        <AdminSidebar />
      </aside>
      <main className="w-full">{children}</main>
    </SidebarProvider>
  );
}
